#! /bin/bash
# Here are the list of version for every part of the deployment

# VERSIONING
# ==========
major_version="0"
minor_version="0"

# Reactive Trader
broker_container_image="reactivetrader/broker"
broker_container_major="0"
broker_container_minor="0"
broker_container="$broker_container_image:$broker_container_major.$broker_container_minor"

populatedeventstore_container_image="reactivetrader/eventstore"
populatedeventstore_container_major="0"
populatedeventstore_container_minor="0"
populatedeventstore_container="$populatedeventstore_container_image:$populatedeventstore_container_major.$populatedeventstore_container_minor"

servers_alias=(analytics blotter pricing referencedataread tradeexecution)
servers_container_image="reactivetrader/servers"
servers_container_major="0"
servers_container_minor="1"
servers_container="$servers_container_image:$servers_container_major.$servers_container_minor"

web_container_image="reactivetrader/web"
web_container_major="0"
web_container_minor="0"
web_container="$web_container_image:$web_container_major.$web_container_minor"

ubuntu_container_image="ubuntu:14"
# Other containers
debian_container_image="debian:8"
# OS
ubuntu_container="$ubuntu_container_image.04.2"
debian_container="$debian_container_image.2"

# crossbar
crossbar_version="17.5.1"
crossbar_container_image="weareadaptive/crossbar"
crossbar_container_major="17"
crossbar_container_minor="5"
crossbar_container="$crossbar_container_image:$crossbar_container_major.$crossbar_container_minor"

# eventstore
eventstore_version="3.3.0"
eventstore_container_image="weareadaptive/eventstore"
eventstore_container_major="0"
eventstore_container_minor="0"
eventstore_container="$eventstore_container_image:$eventstore_container_major.$eventstore_container_minor"

# node
node_version="8"
node_container_image="node"
node_container_major="8"
node_container_minor=""
node_container="$node_container_image:$node_container_major"

# nginx source
nginx_version="1.12.0"
nginxsource_container_image="nginx"
nginxsource_container_major="1"
nginxsource_container_minor="12"
nginxsource_container="$nginxsource_container_image:$nginx_version"

# nginx container
nginx_container_image="weareadaptive/nginx"
nginx_container_major="1"
nginx_container_minor="12"
nginx_container="$nginx_container_image:$nginx_container_major.$nginx_container_minor"

# dotnet
dotnet_apt_package="dotnet-sdk-2.0.0"
dotnet_container_image="weareadaptive/dotnet"
dotnet_container_major="2"
dotnet_container_minor="0"
dotnet_container="$dotnet_container_image:$dotnet_container_major.$dotnet_container_minor"

# TestTool
jq_version="1.5"
testtools_container_image="weareadaptive/testtools"
testtools_container_major="1"
testtools_container_minor="1"
testtools_container="$testtools_container_image:$testtools_container_major.$testtools_container_minor"
testtools_container_latest="$testtools_container_image:latest"

# gcloud
gcloud_container_image="weareadaptive/gcloud"
gcloud_container_major="1"
gcloud_container_minor="2"
gcloud_container="$gcloud_container_image:$gcloud_container_major.$gcloud_container_minor"

# nsgate
nsgate_container_image="weareadaptive/nsgate"
nsgate_container_major="0"
nsgate_container_minor="2"
nsgate_container="$nsgate_container_image:$nsgate_container_major.$nsgate_container_minor"

# minikube
minikubegate_container_image="weareadaptive/minikubegate"
minikubegate_container_major="0"
minikubegate_container_minor="0"
minikubegate_container="$minikubegate_container_image:$minikubegate_container_major.$minikubegate_container_minor"


# GCLOUD
# ======
# other default parameters
kube_project="adaptive-trader"
kube_num_nodes=1

kube_machinetype="n1-standard-1"  #   3.7 Go
# kube_machinetype="n1-highmem-2"   #  13   Go
kube_zone="europe-west1-c"

config_gcloud_externalip_dev="35.195.122.136"
config_gcloud_externalip_cluster="104.155.13.196"

# DOCKER-COMPOSE
# ==============
docker_compose_file="docker-compose.yml"

# LOCAL DOCKER
# ============
docker_network="host"
