#! /bin/bash

echo "Loading containers"

root_directory=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../..")
source ${root_directory}/deploy/config.sh
source ${root_directory}/deploy/touched.sh

mkdir -p ~/docker


for name in ${PULL_LIST[@]}
do
  tag=$(eval "echo \${"${name}Container"}")
  echo docker save ${tag}
  docker save ${tag} > ~/docker/$name.tar && echo "$name saved"
done

for container in ${LOAD_LIST[@]}
do
  # Here ~ refer to the home in circleci
  if [[ -e ~/docker/$container.tar ]]; then
    docker load -i ~/docker/$container.tar && echo "$container loaded"
  fi
done
