#! /bin/bash

if [[ $1 == "" ]];then
  echo "The build number is required for this step"
  exit 1
fi
build=$1

set -eo pipefail

docker login -u $DOCKER_USER -p $DOCKER_PASS

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

source ${root_directory}/deploy/touched.sh

for container in ${BUILD_LIST[@]}
do
  ${root_directory}/deploy/docker/prepare push $container $build
done