#! /bin/bash

. ../config

# Here ~ refer to the home in circleci

mkdir -p ~/docker

echo "Saving containers"
docker save $dotnet_container     > ~/docker/dotnet.tar
docker save $crossbar_container   > ~/docker/crossbar.tar
docker save $eventstore_container > ~/docker/eventstore.tar
docker save $nginx_container      > ~/docker/nginx.tar
