#! /bin/bash

if [[ $# != 1 ]];then
  echo " "
  echo -e "\033[0;32mUsage:\033[0m"
  echo "   ./delete NAMESPACE"
  echo ""
  echo " Will delete an environment"
  exit 1
fi
namespace=$1

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"
${kubectl} delete ns $namespace
