#! /bin/bash

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"

echo -e "\033[0;32mCURRENT CLUSTER\033[0m"
${kubectl} config view | grep current-context:
echo " "

echo -e "\033[0;32mNAMESPACES:\033[0m"
${kubectl} get ns
