#! /bin/bash

if [[ $# != 3 ]];then
  echo " "
  echo -e "\033[0;32mUsage:\033[0m"
  echo "  $0 NAMESPACE SERVICE NEW_BUILD_ID"
  echo " "
  exit 1
fi
namespace=$1
service=$2
build=$3

# fail fast
set -euo pipefail

# load configuration and lib
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config
. ${root_directory}/deploy/kubernetes/helpers/functions.sh

dockerImage=""
if [[ $service == "broker" ]];then
  dockerImage="$broker_container.$build";
fi
if [[ $service == "web" ]];then
  dockerImage="$web_container.$build";
fi
if [[ $service == "eventstore" ]];then
  dockerImage="$populatedeventstore_container.$build";
fi

dotnetServices="analytics blotter pricing referencedataread tradeexecution"
if listcontains "$dotnetServices" $service; then
  dockerImage="$servers_container.$build";
fi

kubectl="${root_directory}/deploy/clis/kubectl"
${kubectl} rolling-update \
  --namespace=$namespace \
  --image=$dockerImage   \
  --update-period=1s     \
  $service
