#! /bin/bash

if [[ $# != 3 ]];then
  echo " "
  echo -e "\033[0;32mUsage:\033[0m"
  echo "  $0 NAMESPACE SERVICE NEW_BUILD_ID"
  echo " "
  exit 1
fi
namespace=$1
service=$2
build=$3

# fail fast
set -euo pipefail

# load configuration and lib
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"

. ${root_directory}/deploy/config
. ${root_directory}/deploy/kubernetes/helpers/functions.sh


sourceName=$service
serverServices="analytics blotter pricing referencedataread tradeexecution"
if listcontains "$serverServices" $service; then
  sourceName="$servers_container.$build";
fi

dockerImage=$(eval "echo \$${sourceName}Container").$build

{
  echo ""
  echo "Performing rolling update for $namespace with $dockerImage on $service"
  ${kubectl} rolling-update --namespace=$namespace --image=$dockerImage --update-period=1s $service
} || {
  echo ""
  echo "Performing rollback then retrying"
  ${kubectl} rolling-update --namespace=$namespace --rollback $service
  ${kubectl} rolling-update --namespace=$namespace --image=$dockerImage --update-period=1s $service
}
